# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '$(Build.SourcesDirectory)/MyFinances/tests/**/*.csproj'
        testRunTitle: 'Running all unit tests'

    - task: Docker@2
      displayName: Build API Image
      inputs:
        command: build
        buildContext: '$(Build.SourcesDirectory)/MyFinances'
        dockerfile: '$(Build.SourcesDirectory)/MyFinances/src/MyFinances.API/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build Blazor Server Image
      inputs:
        command: build
        buildContext: '$(Build.SourcesDirectory)/MyFinances'
        dockerfile: '$(Build.SourcesDirectory)/MyFinances/src/MyFinances.Blazor/Server/Dockerfile'
        tags: |
          $(tag)
