version: '3.4'

services:
  myfinances.api:
    image: ${DOCKER_REGISTRY-}myfinancesapi
    build:
      context: .
      dockerfile: src/MyFinances.API/Dockerfile
    depends_on: [ myfinances.db ]
    ports:
      - 8080:443

  myfinances.db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: Gg@03102020
    ports:
    - 3306:3306 
  myfinances.blazor.server:
    image: ${DOCKER_REGISTRY-}myfinancesblazorserver
    build:
      context: .
      dockerfile: src/MyFinances.Blazor/Server/Dockerfile

    depends_on: [ myfinances.api ]